// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using psicomedixMonolito.DbFiles.Data;

#nullable disable

namespace psicomedixMonolito.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712205857_LineaBasePsicologiaUnificadaV2")]
    partial class LineaBasePsicologiaUnificadaV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.Atencion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoAtencion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HistorialClinicoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObservacionesIniciales")
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicioClinicoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.HasIndex("CodigoAtencion")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("HistorialClinicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ServicioClinicoId");

                    b.ToTable("Atenciones", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoAnamnesisHistoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accidentes")
                        .HasColumnType("text");

                    b.Property<Guid>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CigarrillosVape")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Cirugias")
                        .HasColumnType("text");

                    b.Property<string>("ConsumoOH")
                        .HasColumnType("text");

                    b.Property<string>("Enfermedades")
                        .HasColumnType("text");

                    b.Property<string>("EnfermedadesAccidentesNotasGenerales")
                        .HasColumnType("text");

                    b.Property<string>("FamiliaresAntecedentesRelacionados")
                        .HasColumnType("text");

                    b.Property<string>("Hospitalizacion")
                        .HasColumnType("text");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("text");

                    b.Property<string>("Suplementos")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SustanciasLegales")
                        .HasColumnType("text");

                    b.Property<string>("SustanciasNoLegales")
                        .HasColumnType("text");

                    b.Property<string>("SustanciasNotasGenerales")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId")
                        .IsUnique();

                    b.ToTable("PsicoAnamnesisHistoriales", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoDesarrolloPsicosocial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicoLaboral")
                        .HasColumnType("text");

                    b.Property<Guid>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutoestimaAutocuidado")
                        .HasColumnType("text");

                    b.Property<string>("PersonalidadAutoexpresion")
                        .HasColumnType("text");

                    b.Property<string>("SocializacionFamilia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId")
                        .IsUnique();

                    b.ToTable("PsicoDesarrollosPsicosociales", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoDiagnosticoCierre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiagnosticoDiferencial1")
                        .HasColumnType("text");

                    b.Property<string>("DiagnosticoDiferencial2")
                        .HasColumnType("text");

                    b.Property<string>("DiagnosticoDiferencial3")
                        .HasColumnType("text");

                    b.Property<string>("ImpresionDiagnostica")
                        .HasColumnType("text");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId")
                        .IsUnique();

                    b.ToTable("PsicoDiagnosticosCierres", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoEscalasAnimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EscalaAnsiedad")
                        .HasColumnType("integer");

                    b.Property<int?>("EscalaDesmotivacion")
                        .HasColumnType("integer");

                    b.Property<int?>("EscalaEstres")
                        .HasColumnType("integer");

                    b.Property<int?>("EscalaFatiga")
                        .HasColumnType("integer");

                    b.Property<int?>("EscalaImpulsividad")
                        .HasColumnType("integer");

                    b.Property<int?>("EscalaIrritabilidad")
                        .HasColumnType("integer");

                    b.Property<int?>("EscalaPreocupacion")
                        .HasColumnType("integer");

                    b.Property<int?>("EscalaTristeza")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId")
                        .IsUnique();

                    b.ToTable("PsicoEscalasAnimos", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoEvaluacionCognitiva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BeckAutolesiones")
                        .HasColumnType("text");

                    b.Property<string>("BeckAutolisis")
                        .HasColumnType("text");

                    b.Property<string>("BeckFuturo")
                        .HasColumnType("text");

                    b.Property<string>("BeckMundoExterior")
                        .HasColumnType("text");

                    b.Property<string>("BeckOtros")
                        .HasColumnType("text");

                    b.Property<string>("BeckPersonal")
                        .HasColumnType("text");

                    b.Property<string>("FcAbstraccion")
                        .HasColumnType("text");

                    b.Property<string>("FcAprendizaje")
                        .HasColumnType("text");

                    b.Property<string>("FcAtencion")
                        .HasColumnType("text");

                    b.Property<string>("FcCalculo")
                        .HasColumnType("text");

                    b.Property<string>("FcConcentracion")
                        .HasColumnType("text");

                    b.Property<string>("FcCoordinacionMotoraFina")
                        .HasColumnType("text");

                    b.Property<string>("FcCoordinacionMotoraGruesa")
                        .HasColumnType("text");

                    b.Property<string>("FcEmocion")
                        .HasColumnType("text");

                    b.Property<string>("FcJuicio")
                        .HasColumnType("text");

                    b.Property<string>("FcLenguaje")
                        .HasColumnType("text");

                    b.Property<string>("FcMemoria")
                        .HasColumnType("text");

                    b.Property<string>("FcMotivacion")
                        .HasColumnType("text");

                    b.Property<string>("FcPensamiento")
                        .HasColumnType("text");

                    b.Property<string>("FcPercepcion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId")
                        .IsUnique();

                    b.ToTable("PsicoEvaluacionesCognitivas", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoSomaticoVegetativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adormecimientos")
                        .HasColumnType("text");

                    b.Property<string>("AlimentacionNotasGenerales")
                        .HasColumnType("text");

                    b.Property<string>("AntecedentesAlteracionesClinicas")
                        .HasColumnType("text");

                    b.Property<string>("Apetito")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ApneaSueno")
                        .HasColumnType("text");

                    b.Property<string>("AspectoFisicoActividadFisica")
                        .HasColumnType("text");

                    b.Property<Guid>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cefalea")
                        .HasColumnType("text");

                    b.Property<string>("Ensonaciones")
                        .HasColumnType("text");

                    b.Property<int?>("FrecuenciaCardiaca")
                        .HasColumnType("integer");

                    b.Property<string>("ParalisisSueno")
                        .HasColumnType("text");

                    b.Property<string>("Pesadillas")
                        .HasColumnType("text");

                    b.Property<string>("Peso")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReflejoPupilar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rubefaccion")
                        .HasColumnType("text");

                    b.Property<decimal?>("SaturacionOxigeno")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SignosVitalesNotasGenerales")
                        .HasColumnType("text");

                    b.Property<string>("SignosVitalesOtros")
                        .HasColumnType("text");

                    b.Property<string>("Sobresaltos")
                        .HasColumnType("text");

                    b.Property<string>("SomatizacionesNotasGenerales")
                        .HasColumnType("text");

                    b.Property<string>("SomatizacionesOtros")
                        .HasColumnType("text");

                    b.Property<string>("Sudoracion")
                        .HasColumnType("text");

                    b.Property<string>("SuenoDuracionFin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SuenoDuracionInicio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SuenoNotasGenerales")
                        .HasColumnType("text");

                    b.Property<string>("SuenoOtros")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId")
                        .IsUnique();

                    b.ToTable("PsicoSomaticoVegetativos", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.AjusteFinanciero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoAjuste")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoAjuste")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UsuarioRegistroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PagoId");

                    b.HasIndex("TipoAjuste");

                    b.HasIndex("UsuarioRegistroId");

                    b.ToTable("AjustesFinancieros", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DetalleError")
                        .HasColumnType("text");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsConsulta")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FueExitoso")
                        .HasColumnType("boolean");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("TipoAccion");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaUltimaInteraccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MensajesNoLeidos")
                        .HasColumnType("integer");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelefonoWhatsApp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UltimoMensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoCita")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("HorarioDoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicioClinicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioRegistroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCita")
                        .IsUnique();

                    b.HasIndex("HorarioDoctorId");

                    b.HasIndex("ServicioClinicoId");

                    b.HasIndex("UsuarioRegistroId");

                    b.HasIndex("PacienteId", "Fecha");

                    b.HasIndex("DoctorId", "Fecha", "HoraInicio", "HoraFin");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Comprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoComprobante")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("DatosSnapshotJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("DireccionPaciente")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormatoImpresion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("HistorialClinicoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoImpuesto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroDocumentoPaciente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PagoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TasaImpuesto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TipoDocumentoPaciente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("UsuarioAnulacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioEmisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId");

                    b.HasIndex("CitaId");

                    b.HasIndex("CodigoComprobante")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaEmision");

                    b.HasIndex("HistorialClinicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PagoId");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioEmisionId");

                    b.HasIndex("Serie", "Numero", "TipoComprobante")
                        .IsUnique();

                    b.ToTable("Comprobantes", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ComprobanteDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ComprobanteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("MontoImpuesto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecioUnitarioFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TasaImpuesto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComprobanteId");

                    b.ToTable("ComprobanteDetalles", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CMP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("CodigoDoctor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaFinContrato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicioContrato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CMP")
                        .IsUnique();

                    b.HasIndex("CodigoDoctor")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Doctores", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.HistorialClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoHistorial")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodigoHistorial")
                        .IsUnique();

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("HistorialesClinicos", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.HistorialDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoDetalle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HistorialClinicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PagoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId");

                    b.HasIndex("CitaId");

                    b.HasIndex("CodigoDetalle")
                        .IsUnique();

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("HistorialClinicoId");

                    b.HasIndex("PagoId");

                    b.HasIndex("TipoMovimiento");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialDetalles", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.HorarioDoctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "DiaSemana", "HoraInicio", "HoraFin", "FechaInicioVigencia");

                    b.ToTable("HorariosDoctor", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.MensajeChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsMio")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageIdWhatsApp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("MensajesChat");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.NotificacionCita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaProgramadaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelefonoDestino")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Estado", "FechaProgramadaEnvio");

                    b.ToTable("NotificacionesCitas", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Carrera")
                        .HasColumnType("text");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodigoPaciente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("ConsultaAsuntosLegales")
                        .HasColumnType("boolean");

                    b.Property<string>("DNI")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EdadAnos")
                        .HasColumnType("integer");

                    b.Property<int?>("EdadMeses")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaAtencion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genero")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("GradoInstruccion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GradoSemestreCiclo")
                        .HasColumnType("text");

                    b.Property<decimal?>("IMC")
                        .HasColumnType("numeric");

                    b.Property<string>("InformanteCelular")
                        .HasColumnType("text");

                    b.Property<int?>("InformanteEdad")
                        .HasColumnType("integer");

                    b.Property<string>("InformanteEstadoCivil")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("InformanteNombre")
                        .HasColumnType("text");

                    b.Property<string>("InformanteOcupacion")
                        .HasColumnType("text");

                    b.Property<string>("InformanteParentesco")
                        .HasColumnType("text");

                    b.Property<int?>("IntegrantesFamilia")
                        .HasColumnType("integer");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("text");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("text");

                    b.Property<string>("OtrasEspecialidadesRaw")
                        .HasColumnType("text");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric");

                    b.Property<bool?>("PrimeraAtencionPsicologia")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RecepcionadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Religion")
                        .HasColumnType("text");

                    b.Property<decimal?>("TallaMetros")
                        .HasColumnType("numeric");

                    b.Property<bool?>("TieneInformante")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TieneMasHermanosHijos")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TieneMediosHermanosPadrastros")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPaciente")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("RecepcionadoPorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.PacienteFamiliar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parentesco")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool?>("VivenJuntos")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("PacienteFamiliares", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtencionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("MontoAdelanto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ServicioClinicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioRegistroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId");

                    b.HasIndex("CitaId");

                    b.HasIndex("CodigoPago")
                        .IsUnique();

                    b.HasIndex("FechaPago");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ServicioClinicoId");

                    b.HasIndex("UsuarioRegistroId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.RolPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique();

                    b.ToTable("RolPermisos", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ServicioClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("CostoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("GeneraHistorial")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("RequiereCita")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CodigoServicio")
                        .IsUnique();

                    b.ToTable("ServiciosClinicos", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUsuario")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.Atencion", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Cita", "Cita")
                        .WithOne("Atencion")
                        .HasForeignKey("psicomedixMonolito.Models.ATENCIONES.Atencion", "CitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Doctor", "Doctor")
                        .WithMany("Atenciones")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.HistorialClinico", "HistorialClinico")
                        .WithMany()
                        .HasForeignKey("HistorialClinicoId");

                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithMany("Atenciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.ServicioClinico", "ServicioClinico")
                        .WithMany("Atenciones")
                        .HasForeignKey("ServicioClinicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Doctor");

                    b.Navigation("HistorialClinico");

                    b.Navigation("Paciente");

                    b.Navigation("ServicioClinico");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoAnamnesisHistoria", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithOne("AnamnesisHistoria")
                        .HasForeignKey("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoAnamnesisHistoria", "AtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoDesarrolloPsicosocial", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithOne("DesarrolloPsicosocial")
                        .HasForeignKey("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoDesarrolloPsicosocial", "AtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoDiagnosticoCierre", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithOne("DiagnosticoCierre")
                        .HasForeignKey("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoDiagnosticoCierre", "AtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoEscalasAnimo", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithOne("EscalasAnimo")
                        .HasForeignKey("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoEscalasAnimo", "AtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoEvaluacionCognitiva", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithOne("EvaluacionCognitiva")
                        .HasForeignKey("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoEvaluacionCognitiva", "AtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoSomaticoVegetativo", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithOne("SomaticoVegetativo")
                        .HasForeignKey("psicomedixMonolito.Models.ATENCIONES.AtencionBase.PsicoSomaticoVegetativo", "AtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.AjusteFinanciero", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithMany()
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Pago", "Pago")
                        .WithMany("AjustesFinancieros")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atencion");

                    b.Navigation("Paciente");

                    b.Navigation("Pago");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Auditoria", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Chat", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Cita", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Doctor", "Doctor")
                        .WithMany("Citas")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.HorarioDoctor", "HorarioDoctor")
                        .WithMany("Citas")
                        .HasForeignKey("HorarioDoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.ServicioClinico", "ServicioClinico")
                        .WithMany("Citas")
                        .HasForeignKey("ServicioClinicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("HorarioDoctor");

                    b.Navigation("Paciente");

                    b.Navigation("ServicioClinico");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Comprobante", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithMany("Comprobantes")
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Cita", "Cita")
                        .WithMany("Comprobantes")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.HistorialClinico", "HistorialClinico")
                        .WithMany("Comprobantes")
                        .HasForeignKey("HistorialClinicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithMany("Comprobantes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Pago", "Pago")
                        .WithMany("Comprobantes")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Usuario", "UsuarioAnulacion")
                        .WithMany("ComprobantesAnulados")
                        .HasForeignKey("UsuarioAnulacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Usuario", "UsuarioEmision")
                        .WithMany("ComprobantesEmitidos")
                        .HasForeignKey("UsuarioEmisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atencion");

                    b.Navigation("Cita");

                    b.Navigation("HistorialClinico");

                    b.Navigation("Paciente");

                    b.Navigation("Pago");

                    b.Navigation("UsuarioAnulacion");

                    b.Navigation("UsuarioEmision");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ComprobanteDetalle", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Comprobante", "Comprobante")
                        .WithMany("Detalles")
                        .HasForeignKey("ComprobanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Doctor", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.HistorialClinico", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithOne("HistorialClinico")
                        .HasForeignKey("psicomedixMonolito.Models.HistorialClinico", "PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.HistorialDetalle", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithMany()
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Cita", "Cita")
                        .WithMany("HistorialDetalles")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.HistorialClinico", "HistorialClinico")
                        .WithMany("Detalles")
                        .HasForeignKey("HistorialClinicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Pago", "Pago")
                        .WithMany("HistorialDetalles")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atencion");

                    b.Navigation("Cita");

                    b.Navigation("HistorialClinico");

                    b.Navigation("Pago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.HorarioDoctor", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Doctor", "Doctor")
                        .WithMany("Horarios")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.MensajeChat", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Chat", "Chat")
                        .WithMany("Mensajes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.NotificacionCita", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Cita", "Cita")
                        .WithMany("Notificaciones")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithMany("NotificacionesCita")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Paciente", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("psicomedixMonolito.Models.Usuario", "RecepcionadoPor")
                        .WithMany()
                        .HasForeignKey("RecepcionadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("psicomedixMonolito.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("RecepcionadoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.PacienteFamiliar", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithMany("FamiliaresDirectos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Pago", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.ATENCIONES.Atencion", "Atencion")
                        .WithMany("Pagos")
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Cita", "Cita")
                        .WithMany("Pagos")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("psicomedixMonolito.Models.Paciente", "Paciente")
                        .WithMany("Pagos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.ServicioClinico", "ServicioClinico")
                        .WithMany("Pagos")
                        .HasForeignKey("ServicioClinicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atencion");

                    b.Navigation("Cita");

                    b.Navigation("Paciente");

                    b.Navigation("ServicioClinico");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.RolPermiso", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.UsuarioRol", b =>
                {
                    b.HasOne("psicomedixMonolito.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psicomedixMonolito.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ATENCIONES.Atencion", b =>
                {
                    b.Navigation("AnamnesisHistoria");

                    b.Navigation("Comprobantes");

                    b.Navigation("DesarrolloPsicosocial");

                    b.Navigation("DiagnosticoCierre");

                    b.Navigation("EscalasAnimo");

                    b.Navigation("EvaluacionCognitiva");

                    b.Navigation("Pagos");

                    b.Navigation("SomaticoVegetativo");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Chat", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Cita", b =>
                {
                    b.Navigation("Atencion");

                    b.Navigation("Comprobantes");

                    b.Navigation("HistorialDetalles");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Comprobante", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Doctor", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("Citas");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.HistorialClinico", b =>
                {
                    b.Navigation("Comprobantes");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.HorarioDoctor", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Paciente", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("Citas");

                    b.Navigation("Comprobantes");

                    b.Navigation("FamiliaresDirectos");

                    b.Navigation("HistorialClinico");

                    b.Navigation("NotificacionesCita");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Pago", b =>
                {
                    b.Navigation("AjustesFinancieros");

                    b.Navigation("Comprobantes");

                    b.Navigation("HistorialDetalles");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.ServicioClinico", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("Citas");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("psicomedixMonolito.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("ComprobantesAnulados");

                    b.Navigation("ComprobantesEmitidos");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
